# ---- Build stage: regenerate the generated HTML from data/cases.js ----
# scripts/build-home.mjs, build-noscript.mjs and build-case-pages.mjs are
# pure Node with zero npm dependencies (there's no package.json in this
# repo, on purpose — the site itself ships zero runtime deps, and these
# three scripts only use node:fs/node:path/node:url plus the project's
# own data/cases.js and js/case-utils.js). This stage exists only to run
# them against a copy of the repo before anything is served, so a deploy
# can never ship a home page or case pages that have drifted out of sync
# with data/cases.js the way the hand-written fallbacks once did.
#
# build-case-pages.mjs runs with --allow-drafts here specifically —
# without it, an incomplete P0 case fails the build outright, which is
# exactly right for a human running it locally (the guard against
# shipping placeholder content by accident) but wrong for a deploy
# pipeline, which has no way to act on that prompt. --allow-drafts keeps
# every page generating (still with a loud draft banner and NEEDS-INPUT
# flagging on anything incomplete) without failing the container build.
#
# build-og-images.mjs deliberately does NOT run here — it requires
# Playwright, which is not and should not become part of this build; OG
# images are pre-generated, real, committed static assets already (see
# that script's own header comment), regenerated by hand only when case
# content changes enough to need new ones.
FROM node:20-alpine AS build
WORKDIR /site
COPY . .
RUN node scripts/build-home.mjs && \
    node scripts/build-noscript.mjs && \
    node scripts/build-case-pages.mjs --allow-drafts

# ---- Serve stage: Caddy serving the generated static site ----
FROM caddy:2-alpine
COPY --from=build /site /srv
COPY Caddyfile /etc/caddy/Caddyfile
